# Generated by Django 2.2.12 on 2020-05-08 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Table number. Ensure this value is greater than or equal to 1.', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('seats', models.PositiveIntegerField(help_text='Seats quantity. Ensure this value is greater than or equal to 1.', validators=[django.core.validators.MinValueValidator(1)])),
                ('shape', models.CharField(choices=[('rectangular', 'rectangular'), ('oval', 'oval')], max_length=50)),
                ('coordinate_x', models.DecimalField(decimal_places=2, max_digits=4)),
                ('coordinate_y', models.DecimalField(decimal_places=2, max_digits=4)),
                ('width', models.DecimalField(decimal_places=2, help_text='size data in meters', max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, help_text='size data in meters', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, help_text='Order created at')),
                ('order_date', models.DateField(help_text='Order on')),
                ('additional_info', models.TextField(blank=True, help_text='Additional information')),
                ('order_by_name', models.CharField(help_text='Guest name', max_length=100)),
                ('order_by_email', models.EmailField(help_text='Guest email', max_length=254)),
                ('table', models.ForeignKey(help_text='Table number', on_delete=django.db.models.deletion.CASCADE, to='main.Table')),
            ],
            options={
                'unique_together': {('table', 'order_date')},
            },
        ),
    ]
